### ISSUE TITLE
Found a problem with URLs

### ISSUE THREAD

**Issue by MDominicG** [aeberdinelli/express-php#9]
Hey! First of all, thank you for your amazing framework. You did a great job.

Now, I found a problem. I'm using your framework to build an e-commerce website and I have different products with different part numbers.
Here are a few examples:
-> 0 986 479 R67 - Working
-> 09.8137.76 - Not Working

The problem is with the dot ( . ) it's not working with the match function. 

I'm getting this error: **Cannot GET product09.8137.7665**
While the URL looks like so: **http://localhost/product/09.8137.76/65**

My routing code is looking like this:
```
$app->get('/product/[:articleid]/[:brandname]', function($req, $res){
    $articleid      = rawurldecode($req->params['articleid']);
    $brandid        = rawurldecode($req->params['brandname']);
    if(Core::AllowUserAccessOffline())    
        $res->render('autoparts_product',  [
            "ArticleID"         =>      $articleid,
            "BrandID"           =>      $brandid,
        ]);
    else
        $res->render('offline');
});
```

**Comment by aeberdinelli** [comment]
Hello! Thanks for your taking a look at my framework. Here's a couple comments that might help:

1. First of all, keep in mind this was made 4 years ago and I'm no longer maintaining it 🙁
2. If you still want to use it: the regex that the library uses doesn't include a dot (`.`) as an acceptable character. In order to make it work, you should change the regular expression in this constant: https://github.com/aeberdinelli/express-php/blob/master/src/Express/Express.php#L19
3. The easiest option is to change your dot to something else, like a `-`. That character is supported by default and you don't need to do any deep changes.

Let me know if that helps!
